# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-04 19:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100, verbose_name='E-mail')),
                ('added_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data dodania')),
            ],
        ),
        migrations.CreateModel(
            name='DiscountCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=1000, verbose_name='Kod rabatowy')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktywny')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='discount_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.DiscountCode', verbose_name='Kod rabatowy'),
        ),
    ]
