# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-05 12:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20180104_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='fb_id',
            field=models.CharField(max_length=100, unique=True, verbose_name='Facebook ID'),
            preserve_default=False,
        ),
    ]
